version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/eng/dependabot"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "dependabot: main"

  - package-ecosystem: "nuget"
    directory: "/eng/dependabot"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    target-branch: "release/8.0.1xx"
    labels:
      - "dependencies"
      - "dependabot: 8.0.1xx"
